#![warn(clippy::pedantic)]

use std::{
    collections::HashSet,
    sync::{Arc, LazyLock},
    time::{Duration, SystemTime},
};

use anyhow::{Result, bail};
use axum::{
    Json, Router,
    body::Body,
    extract::{Request, State},
    http::HeaderName,
    middleware::{self, Next},
    response::{IntoResponse, Response},
    routing::{get, post},
};
use bon::bon;
use clap::Parser;
use reqwest::header::{self};
use reqwest::{Client, RequestBuilder, StatusCode};
use serde_json::{Value, json};
use tracing::{Level, event};
use tracing_subscriber::prelude::*;
use tracing_subscriber::{EnvFilter, fmt};

use crate::config::{Config, ModelTarget, ProcessedConfig};

mod config;

const DEFAULT_CONNECT_TIMEOUT: Duration = Duration::from_secs(30);
const DEFAULT_READ_TIMEOUT: Duration = Duration::from_mins(5);
const DEFAULT_TOTAL_TIMEOUT: Duration = Duration::from_mins(10);

// Since we're basically behaving as an HTTP proxy, we're not supposed
// to propagate "hop-by-hop" headers from the origin HTTP server.
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Connection
static HOP_BY_HOP_HEADERS: LazyLock<HashSet<HeaderName>> = LazyLock::new(|| {
    let mut headers = HashSet::new();
    headers.insert(header::TRANSFER_ENCODING);
    headers.insert(header::TE);
    headers.insert(header::CONNECTION);
    headers.insert(header::TRAILER);
    headers.insert(header::UPGRADE);
    headers.insert(header::PROXY_AUTHORIZATION);
    headers.insert(header::PROXY_AUTHENTICATE);
    // Oddly, there's no constant for arguably the most ubiquitous one?
    headers.insert(HeaderName::from_static("keep-alive"));
    headers
});

#[derive(Debug, Clone, Parser)]
#[command(name = "simple-llm-proxy")]
struct Args {
    #[arg(long, default_value = "127.0.0.1")]
    host: String,
    #[arg(long, default_value = "3000")]
    port: u16,
}

#[derive(Debug)]
struct LlmProxy {
    client: Client,
    config: ProcessedConfig,
    start_time: Duration,
}

// I saw the "maybe_*" methods generated by bun and missed having them
// on RequestBuilder
trait RequestBuilderExt {
    fn maybe_bearer_auth(self, token: Option<&str>) -> RequestBuilder;
}

impl RequestBuilderExt for RequestBuilder {
    fn maybe_bearer_auth(self, token: Option<&str>) -> RequestBuilder {
        if let Some(tok) = token {
            self.bearer_auth(tok)
        } else {
            self
        }
    }
}

#[bon]
impl LlmProxy {
    #[builder]
    fn new(
        config: Config,
        connect_timeout: Option<Duration>,
        read_timeout: Option<Duration>,
        total_timeout: Option<Duration>,
    ) -> Self {
        let client = Client::builder()
            .connect_timeout(connect_timeout.unwrap_or(DEFAULT_CONNECT_TIMEOUT))
            .read_timeout(read_timeout.unwrap_or(DEFAULT_READ_TIMEOUT))
            .timeout(total_timeout.unwrap_or(DEFAULT_TOTAL_TIMEOUT))
            .build()
            .unwrap();

        let processed_config = config.process_config();

        let epoch_time = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap();

        Self {
            client,
            config: processed_config,
            start_time: epoch_time,
        }
    }

    fn endpoint(base_url: &str, path: &str) -> String {
        // TODO there's probably a way to ensure the result is still valid
        let mut result = String::new();
        // Assumes base_url has already been right-stripped of /
        result.push_str(base_url);
        result.push_str(path);
        result
    }

    // Generate an (axum) Response from a reqwest Response, preserving
    // status code and (non-hop-by-hop) headers.
    // We simply stream the body over, which seems to handle SSE responses
    // just fine.
    fn make_proxy_response(orig_resp: reqwest::Response) -> Response {
        let mut resp_builder = Response::builder().status(orig_resp.status());
        {
            let headers = resp_builder.headers_mut().unwrap();
            for (k, v) in orig_resp.headers() {
                if !HOP_BY_HOP_HEADERS.contains(k) {
                    headers.append(k, v.clone());
                }
            }
        }
        resp_builder
            .body(Body::from_stream(orig_resp.bytes_stream()))
            .unwrap()
    }

    async fn post_proxy(
        &self,
        base_url: &str,
        api_key: Option<&str>,
        path: &str,
        Json(payload): Json<Value>,
    ) -> Result<Response> {
        event!(Level::DEBUG, "proxying POST to {base_url} {path}");
        let orig_resp = self
            .client
            .post(LlmProxy::endpoint(base_url, path))
            .maybe_bearer_auth(api_key)
            .json(&payload)
            .send()
            .await?;
        Ok(Self::make_proxy_response(orig_resp))
    }

    #[allow(dead_code)]
    async fn get_proxy(
        &self,
        base_url: &str,
        api_key: Option<&str>,
        path: &str,
    ) -> Result<Response> {
        let orig_resp = self
            .client
            .get(LlmProxy::endpoint(base_url, path))
            .maybe_bearer_auth(api_key)
            .send()
            .await?;
        Ok(Self::make_proxy_response(orig_resp))
    }

    fn bad_request(message: &str) -> Response {
        (
            StatusCode::BAD_REQUEST,
            Json(json!({"error":{"message":message}})),
        )
            .into_response()
    }

    fn remap_model(&self, input: &mut Value) -> Result<(ModelTarget, Value)> {
        if let Some(model_target) = input
            .get("model")
            .and_then(|m| m.as_str().and_then(|mt| self.config.get_target(mt)))
        {
            let input_map = input.as_object_mut().unwrap();
            input_map.insert(
                "model".to_owned(),
                Value::String(model_target.model.clone()),
            );
            let output = Value::Object(input_map.clone());
            Ok((model_target, output))
        } else {
            bail!("error mapping model")
        }
    }

    async fn chat_handler(
        State(state): State<Arc<LlmProxy>>,
        Json(mut payload): Json<Value>,
    ) -> Response {
        match state.remap_model(&mut payload) {
            Ok((model_target, new_payload)) => match state
                .post_proxy(
                    &model_target.base_url,
                    model_target.api_key.as_deref(),
                    "/chat/completions",
                    Json(new_payload),
                )
                .await
            {
                Ok(resp) => resp,
                Err(e) => {
                    event!(Level::ERROR, "post_proxy failed: {e}");
                    (
                        StatusCode::INTERNAL_SERVER_ERROR,
                        Json(json!({"error":{"message":e.to_string()}})).into_response(),
                    )
                        .into_response()
                }
            },
            Err(e) => LlmProxy::bad_request(&e.to_string()),
        }
    }

    fn model_handler(
        State(state): State<Arc<LlmProxy>>,
    ) -> impl std::future::Future<Output = Response> {
        let mut resp_map = serde_json::Map::new();
        resp_map.insert("object".to_owned(), Value::String("list".to_owned()));

        let mut models = Vec::new();
        for m in state.config.get_models() {
            let mut model_map = serde_json::Map::new();
            model_map.insert("id".to_owned(), Value::String(m.clone()));
            model_map.insert("object".to_owned(), Value::String("model".to_owned()));
            model_map.insert("created".to_owned(), json!(state.start_time.as_secs()));
            model_map.insert(
                "owned_by".to_owned(),
                Value::String("simple-llm-proxy".to_owned()),
            ); // FIXME magic string
            models.push(Value::Object(model_map));
        }

        resp_map.insert("data".to_owned(), Value::Array(models));

        std::future::ready(Json(Value::Object(resp_map)).into_response())
    }

    fn check_auth<B>(&self, request: &Request<B>) -> impl Future<Output = bool> {
        let token = if let Some(maybe_token) = request.headers().get(header::AUTHORIZATION) {
            match maybe_token.to_str() {
                Ok(header) => header.strip_prefix("Bearer ").map(str::trim),
                Err(_) => None,
            }
        } else {
            None
        };
        std::future::ready(self.config.auth_check(token))
    }
}

async fn shutdown_signal() {
    let ctrl_c = async {
        tokio::signal::ctrl_c()
            .await
            .expect("failed to install Ctrl+C handler");
    };

    #[cfg(unix)]
    let terminate = async {
        tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
            .expect("failed to install signal handler")
            .recv()
            .await;
    };

    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();

    tokio::select! {
        () = ctrl_c => {},
        () = terminate => {},
    }
}

async fn my_auth_middleware(
    State(state): State<Arc<LlmProxy>>,
    request: Request,
    next: Next,
) -> Response {
    if state.check_auth(&request).await {
        next.run(request).await
    } else {
        (
            StatusCode::UNAUTHORIZED,
            Json(json!({"error":{"message":"unauthorized"}})),
        )
            .into_response()
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let fmt_layer = fmt::layer().with_target(false);
    let filter_layer = EnvFilter::try_from_default_env()
        .or_else(|_| EnvFilter::try_new("info"))
        .unwrap();

    tracing_subscriber::registry()
        .with(filter_layer)
        .with(fmt_layer)
        .init();

    let args = Args::parse();
    let bind_addr = format!("{}:{}", args.host, args.port);

    let config = Config::load("config.yaml")?;

    event!(Level::INFO, "Listening on {bind_addr}");
    event!(
        Level::DEBUG,
        "connect/read/total timeouts: {:?}/{:?}/{:?}",
        config.connect_timeout,
        config.read_timeout,
        config.total_timeout
    );

    let model_gateway = LlmProxy::builder()
        .maybe_connect_timeout(config.connect_timeout.map(Duration::from_secs))
        .maybe_read_timeout(config.read_timeout.map(Duration::from_secs))
        .maybe_total_timeout(config.total_timeout.map(Duration::from_secs))
        .config(config)
        .build();

    let shared_model_gateway = Arc::new(model_gateway);

    let app = Router::new()
        .route("/v1/models", get(LlmProxy::model_handler))
        .route("/v1/chat/completions", post(LlmProxy::chat_handler))
        .layer(middleware::from_fn_with_state(
            shared_model_gateway.clone(),
            my_auth_middleware,
        ))
        .with_state(shared_model_gateway);

    let listener = tokio::net::TcpListener::bind(&bind_addr).await?;
    axum::serve(listener, app)
        .with_graceful_shutdown(shutdown_signal())
        .await?;

    event!(Level::INFO, "Exiting...");

    Ok(())
}
