#![warn(clippy::pedantic)]

use std::{
    collections::{HashMap, HashSet},
    sync::{Arc, LazyLock},
    time::{Duration, SystemTime},
};

use anyhow::{Context, Result, bail};
use axum::{
    Json, Router,
    body::Body,
    extract::{Request, State},
    http::HeaderName,
    middleware::{self, Next},
    response::{IntoResponse, Response},
    routing::{get, post},
};
use bon::bon;
use clap::Parser;
use moka::future::Cache;
use reqwest::header::{self};
use reqwest::{Client, RequestBuilder, StatusCode};
use serde_json::{Value, json};
use tracing::{Level, event};
use tracing_subscriber::prelude::*;
use tracing_subscriber::{EnvFilter, fmt};

use crate::config::{Config, ModelTarget, ProcessedConfig, ProcessedRemap};

mod config;

const DEFAULT_CONNECT_TIMEOUT: Duration = Duration::from_secs(30);
const DEFAULT_READ_TIMEOUT: Duration = Duration::from_mins(5);
const DEFAULT_TOTAL_TIMEOUT: Duration = Duration::from_mins(10);

// Since we're basically behaving as an HTTP proxy, we're not supposed
// to propagate "hop-by-hop" headers from the origin HTTP server.
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Connection
static HOP_BY_HOP_HEADERS: LazyLock<HashSet<HeaderName>> = LazyLock::new(|| {
    let mut headers = HashSet::new();
    headers.insert(header::TRANSFER_ENCODING);
    headers.insert(header::TE);
    headers.insert(header::CONNECTION);
    headers.insert(header::TRAILER);
    headers.insert(header::UPGRADE);
    headers.insert(header::PROXY_AUTHORIZATION);
    headers.insert(header::PROXY_AUTHENTICATE);
    // Oddly, there's no constant for arguably the most ubiquitous one?
    headers.insert(HeaderName::from_static("keep-alive"));
    headers
});

#[derive(Debug, Clone, Parser)]
#[command(name = "simple-llm-proxy")]
struct Args {
    #[arg(long, default_value = "127.0.0.1")]
    host: String,
    #[arg(long, default_value = "3000")]
    port: u16,
}

#[derive(Debug)]
struct LlmProxy {
    client: Client,
    config: ProcessedConfig,
    start_time: Duration,
    response_cache: Cache<String, Value>,
}

type MyState = Arc<LlmProxy>;

// I saw the "maybe_*" methods generated by bun and missed having them
// on RequestBuilder
trait RequestBuilderExt {
    fn maybe_bearer_auth(self, token: Option<&str>) -> RequestBuilder;
}

impl RequestBuilderExt for RequestBuilder {
    fn maybe_bearer_auth(self, token: Option<&str>) -> RequestBuilder {
        if let Some(tok) = token {
            self.bearer_auth(tok)
        } else {
            self
        }
    }
}

#[bon]
impl LlmProxy {
    #[builder]
    fn new(
        config: Config,
        connect_timeout: Option<Duration>,
        read_timeout: Option<Duration>,
        total_timeout: Option<Duration>,
    ) -> Self {
        let client = Client::builder()
            .connect_timeout(connect_timeout.unwrap_or(DEFAULT_CONNECT_TIMEOUT))
            .read_timeout(read_timeout.unwrap_or(DEFAULT_READ_TIMEOUT))
            .timeout(total_timeout.unwrap_or(DEFAULT_TOTAL_TIMEOUT))
            .build()
            .unwrap();

        let processed_config = config.process_config();

        let epoch_time = SystemTime::now()
            .duration_since(SystemTime::UNIX_EPOCH)
            .unwrap();

        // TODO configure this somehow
        let response_cache = Cache::builder()
            .time_to_live(Duration::from_hours(1))
            .build();

        Self {
            client,
            config: processed_config,
            start_time: epoch_time,
            response_cache,
        }
    }

    fn endpoint(base_url: &str, path: &str) -> String {
        // TODO there's probably a way to ensure the result is still valid
        let mut result = String::new();
        // Assumes base_url has already been right-stripped of /
        result.push_str(base_url);
        result.push_str(path);
        result
    }

    // Generate an (axum) Response from a reqwest Response, preserving
    // status code and (non-hop-by-hop) headers.
    // We simply stream the body over, which seems to handle SSE responses
    // just fine.
    fn make_proxy_response(orig_resp: reqwest::Response) -> Response {
        let mut resp_builder = Response::builder().status(orig_resp.status());
        {
            let headers = resp_builder.headers_mut().unwrap();
            for (k, v) in orig_resp.headers() {
                if !HOP_BY_HOP_HEADERS.contains(k) {
                    headers.append(k, v.clone());
                }
            }
        }
        resp_builder
            .body(Body::from_stream(orig_resp.bytes_stream()))
            .unwrap()
    }

    async fn post_proxy(
        &self,
        base_url: &str,
        api_key: Option<&str>,
        path: &str,
        Json(payload): Json<Value>,
    ) -> Result<Response> {
        event!(Level::DEBUG, "proxying POST to {base_url} {path}");
        let orig_resp = self
            .client
            .post(Self::endpoint(base_url, path))
            .maybe_bearer_auth(api_key)
            .json(&payload)
            .send()
            .await?;
        Ok(Self::make_proxy_response(orig_resp))
    }

    #[allow(dead_code)]
    async fn get_proxy(
        &self,
        base_url: &str,
        api_key: Option<&str>,
        path: &str,
    ) -> Result<Response> {
        let orig_resp = self
            .client
            .get(Self::endpoint(base_url, path))
            .maybe_bearer_auth(api_key)
            .send()
            .await?;
        Ok(Self::make_proxy_response(orig_resp))
    }

    fn bad_request(message: &str) -> Response {
        (
            StatusCode::BAD_REQUEST,
            Json(json!({"error":{"message":message}})),
        )
            .into_response()
    }

    async fn remap_model(&self, input: &mut Value) -> Result<(ModelTarget, Value, String)> {
        if let Some(json_model) = &mut input.get("model").and_then(|m| m.as_str()) {
            let received_model = json_model.to_owned();
            if let Some(model_target) = self.config.get_target(&received_model).await {
                let input_map = input.as_object_mut().unwrap();
                input_map.insert(
                    "model".to_owned(),
                    Value::String(model_target.model.clone()),
                );
                let output = Value::Object(input_map.clone());
                Ok((model_target, output, received_model))
            } else {
                bail!("unknown model")
            }
        } else {
            bail!("missing model")
        }
    }

    async fn post_handler(&self, mut payload: Value, endpoint: &str) -> Response {
        match self.remap_model(&mut payload).await {
            Ok((model_target, new_payload, _received_model)) => match self
                .post_proxy(
                    &model_target.base_url,
                    model_target.api_key.as_deref(),
                    endpoint,
                    Json(new_payload),
                )
                .await
            {
                Ok(resp) => resp,
                Err(e) => {
                    event!(Level::ERROR, "post_proxy failed: {e}");
                    (
                        StatusCode::INTERNAL_SERVER_ERROR,
                        Json(json!({"error":{"message":e.to_string()}})).into_response(),
                    )
                        .into_response()
                }
            },
            Err(e) => Self::bad_request(&e.to_string()),
        }
    }

    async fn completions_handler(
        State(state): State<MyState>,
        Json(payload): Json<Value>,
    ) -> Response {
        state.post_handler(payload, "/completions").await
    }

    async fn chat_handler(State(state): State<MyState>, Json(payload): Json<Value>) -> Response {
        state.post_handler(payload, "/chat/completions").await
    }

    // TODO possibly unfinished, see further in
    async fn responses_handler(
        State(state): State<MyState>,
        Json(mut payload): Json<Value>,
    ) -> Response {
        match state.remap_model(&mut payload).await {
            Ok((model_target, new_payload, _received_model)) => match state
                .post_proxy(
                    &model_target.base_url,
                    model_target.api_key.as_deref(),
                    "/responses",
                    Json(new_payload),
                )
                .await
            {
                Ok(resp) => {
                    // TODO Swap received_model back into the response.
                    // Though does it really matter? Would clients care?
                    // Unfortunately, the possibility of streaming makes
                    // this a far more difficult problem.
                    // (Because each "data" event is a JSON response with
                    // the final one most likely containing the model.)
                    // We would need full SSE parsing.
                    resp
                }
                Err(e) => {
                    event!(Level::ERROR, "post_proxy failed: {e}");
                    (
                        StatusCode::INTERNAL_SERVER_ERROR,
                        Json(json!({"error":{"message":e.to_string()}})).into_response(),
                    )
                        .into_response()
                }
            },
            Err(e) => Self::bad_request(&e.to_string()),
        }
    }

    async fn model_handler(State(state): State<MyState>) -> Response {
        state.update_remaps().await;

        let mut resp_map = serde_json::Map::new();
        resp_map.insert("object".to_owned(), Value::String("list".to_owned()));

        let mut models = Vec::new();
        for m in state.config.get_models().await {
            let mut model_map = serde_json::Map::new();
            model_map.insert("id".to_owned(), Value::String(m.clone()));
            model_map.insert("object".to_owned(), Value::String("model".to_owned()));
            model_map.insert("created".to_owned(), json!(state.start_time.as_secs()));
            model_map.insert(
                "owned_by".to_owned(),
                Value::String("simple-llm-proxy".to_owned()),
            ); // FIXME magic string
            models.push(Value::Object(model_map));
        }

        resp_map.insert("data".to_owned(), Value::Array(models));

        Json(Value::Object(resp_map)).into_response()
    }

    fn check_auth(&self, request: &Request) -> impl Future<Output = bool> {
        let token = request
            .headers()
            .get(header::AUTHORIZATION)
            .and_then(|value| value.to_str().ok())
            .and_then(|header| header.strip_prefix("Bearer ").map(str::trim));
        std::future::ready(self.config.auth_check(token))
    }

    fn health_check(State(_state): State<MyState>) -> impl Future<Output = Response> {
        // Configuration has been fully parsed and processed at this point,
        // so there isn't much left to do.
        // TODO Maybe hit /v1/models endpoint on select providers? (Not
        // all will necessarily have one. Plus more traffic.)
        std::future::ready(Json(json!({"status":"still alive"})).into_response())
    }

    async fn query_provider(&self, remap: &ProcessedRemap) -> Result<Value> {
        let resp = self
            .client
            .get(Self::endpoint(&remap.base_url, "/models"))
            .maybe_bearer_auth(remap.api_key.as_deref())
            .send()
            .await?;
        resp.json()
            .await
            .with_context(|| "failed to deserialize response")
    }

    async fn update_remaps(&self) {
        let mut recompute = false;
        let my_cache = self.response_cache.clone();

        let mut values = HashMap::new();

        for remap in &self.config.remaps {
            // FIXME doesn't deal with duplicate providers very well (though still correct)
            let maybe_entry = my_cache
                .entry(remap.provider.clone())
                .or_optionally_insert_with(async {
                    if let Ok(value) = self.query_provider(remap).await {
                        Some(value)
                    } else {
                        event!(
                            Level::WARN,
                            "failed to query /models endpoint for provider '{}'",
                            remap.provider
                        );
                        None
                    }
                })
                .await;
            if let Some(entry) = maybe_entry {
                if entry.is_fresh() {
                    recompute = true;
                }
                values.insert(remap.provider.clone(), entry.into_value());
            }
        }

        if recompute {
            // Remember: Whatever duplication prevention happens above must
            // not be done here. Remaps pointing to the same provider will
            // most likely have different filters.
            for remap in &self.config.remaps {
                if let Some(source) = values.get(&remap.provider)
                    && remap.populate(source).await.is_err()
                {
                    event!(
                        Level::WARN,
                        "bad response from /models endpoint from provider '{}'",
                        remap.provider
                    );
                }
            }

            self.config.update_models().await;
        }
    }
}

async fn shutdown_signal() {
    let ctrl_c = async {
        tokio::signal::ctrl_c()
            .await
            .expect("failed to install Ctrl+C handler");
    };

    #[cfg(unix)]
    let terminate = async {
        tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
            .expect("failed to install signal handler")
            .recv()
            .await;
    };

    #[cfg(not(unix))]
    let terminate = std::future::pending::<()>();

    tokio::select! {
        () = ctrl_c => {},
        () = terminate => {},
    }
}

async fn my_auth_middleware(
    State(state): State<MyState>,
    request: Request,
    next: Next,
) -> Response {
    if state.check_auth(&request).await {
        next.run(request).await
    } else {
        (
            StatusCode::UNAUTHORIZED,
            Json(json!({"error":{"message":"unauthorized"}})),
        )
            .into_response()
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    let fmt_layer = fmt::layer().with_target(false);
    let filter_layer = EnvFilter::try_from_default_env()
        .or_else(|_| EnvFilter::try_new("info"))
        .unwrap();

    tracing_subscriber::registry()
        .with(filter_layer)
        .with(fmt_layer)
        .init();

    let args = Args::parse();
    let bind_addr = format!("{}:{}", args.host, args.port);

    let config = Config::load("config.yaml")?;

    event!(Level::INFO, "Listening on {bind_addr}");
    event!(
        Level::DEBUG,
        "connect/read/total timeouts: {:?}/{:?}/{:?}",
        config.connect_timeout,
        config.read_timeout,
        config.total_timeout
    );

    let model_gateway = LlmProxy::builder()
        .maybe_connect_timeout(config.connect_timeout.map(Duration::from_secs))
        .maybe_read_timeout(config.read_timeout.map(Duration::from_secs))
        .maybe_total_timeout(config.total_timeout.map(Duration::from_secs))
        .config(config)
        .build();

    let shared_model_gateway = Arc::new(model_gateway);

    let app = Router::new()
        .route("/v1/models", get(LlmProxy::model_handler))
        .route("/v1/completions", post(LlmProxy::completions_handler))
        .route("/v1/chat/completions", post(LlmProxy::chat_handler))
        .route("/v1/responses", post(LlmProxy::responses_handler))
        .layer(middleware::from_fn_with_state(
            shared_model_gateway.clone(),
            my_auth_middleware,
        ))
        .route("/health", get(LlmProxy::health_check))
        .with_state(shared_model_gateway);

    let listener = tokio::net::TcpListener::bind(&bind_addr).await?;
    axum::serve(listener, app)
        .with_graceful_shutdown(shutdown_signal())
        .await?;

    event!(Level::INFO, "Exiting...");

    Ok(())
}
